name: polymer
version: 0.5.3
author: Web UI Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://github.com/dart-lang/web-ui
environment:
  sdk: '>=0.6.15+1'
dependencies:
  analyzer_experimental: '>=0.6.13'
  args: '>=0.6.13'
  barback: '>=0.6.13'
  browser: '>=0.6.13'
  codegen: '>=0.6.13'
  custom_element: '>=0.6.15+2'
  fancy_syntax: '>=0.0.6'
  html_import: '>=0.6.13'
  logging: '>=0.6.13'
  mdv: '>=0.6.15+2'
  observe: '>=0.6.15+2'
  path: '>=0.6.13'
  shadow_dom: '>=0.6.13'
  source_maps: '>=0.6.13'
  unittest: '>=0.6.13'
  # Pin these github packages so we don't get breaks from publishing them:
  csslib: '>=0.4.7 <0.4.8'
  html5lib: '>=0.4.4 <0.4.5'
dev_dependencies:
  benchmark_harness: '>=1.0.2 <1.0.3'
