name: polymer
author: "Web UI Authors <web-ui-dev@dartlang.org>"
homepage: https://github.com/dart-lang/web-ui
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
version: 0.5.1
dependencies:
  args: ">=0.4.5"
  analyzer_experimental: ">=0.5.12"
  browser: ">=0.4.5"
  logging: ">=0.4.5"
  mdv: ">=0.6.9+2"
  observe: ">=0.6.2"
  pathos: ">=0.4.5"
  shadow_dom: ">=0.6.9+2"
  unittest: ">=0.4.5"
  # Pin these github packages so we don't get breaks from publishing them:
  csslib: ">=0.4.7 <0.4.8"
  html5lib: ">=0.4.3 <0.4.4"
  source_maps: ">=0.4.5"
dev_dependencies:
  js: any
  benchmark_harness: ">=1.0.2 <1.0.3"
environment:
  sdk: ">=0.6.9+2"
